config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root to: 'narrates#home'
  resources :narrates do
    collection do
      post :confirm
    end
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/inbox"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :narrate
end

app/models/narrate.rb
class Narrate < ApplicationRecord
  mount_uploader :image, NarrateImageUploader

  belongs_to :user
  has_many :favorites,dependent: :destroy
  has_many :favorite_users,through: :faorites, source: :user
  validates :content, length: {in: 1..140}
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :narrates
  has_many :favorites,dependent: :destroy
  has_many :favorite_narrates, through: :favorites , source: :narrate

  validates :name, presence: true, length: { maximum: 10 }
  validates :email, presence: true, length: { maximum: 255},format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(narrate_id: params[:narrate_id])
    redirect_to narrates_path, notice: "#{favorite.narrate.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to narrates_path, notice: "#{favorite.narrate.user.name}さんのブログをお気に入り解除しました"
  end

end

app/controllers/narrates_controller.rb
class NarratesController < ApplicationController
  before_action :set_narrate,only:[:edit,:update,:destroy]
  before_action :login_sender,only:[:confirm,:index,:create,:new,:edit,:update,:destroy]

  def home
  end

  def confirm
    @narrate = Narrate.new(narrate_params)
    @user = current_user
    @narrate.user_id = current_user.id
    render :new if @narrate.invalid?
  end

  def index
    @narrates = Narrate.all
  end

  def create
    @narrate = Narrate.create(narrate_params)
    @narrate.user_id = current_user.id
    @current_user = current_user
    if @narrate.save
      ContributeMailer.contribute_mail(@narrate,@current_user).deliver
      redirect_to narrates_path,notice:"つぶやきを新しく投稿しました！"
    else
      render'new'
    end
  end

  def new
    if params[:back]
      @narrate = Narrate.new(narrate_params)
    else
      @narrate = Narrate.new
    end
  end

  def edits
  end

  def update
    if @narrate.update(narrate_params)
      redirect_to narrates_path,notice:"編集しました！"
    else
      render'edit'
    end
  end

  def destroy
    @narrate.destroy
    redirect_to narrates_path,notice:"削除しました！"
  end

  private
  def narrate_params
    params.require(:narrate).permit(:content, :user_id,:image,:image_cache)
  end

  def set_narrate
    @narrate = Narrate.find(params[:id])
  end

  def login_sender
    if logged_in?
    else
      redirect_to new_session_path,notice:"Narraterを使うにはログインしてください"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @fav_narrates = @user.favorite_narrates
  end

  def update
    @user = User.find(params[:id])
    @user.password = @user.password_digest
    @user.update(user_params)
    redirect_to user_path,notice:"アイコンを変更しました！"
  end


  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:image, :image_cache)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/narrates_helper.rb
module NarratesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_narrates_path
    elsif action_name == 'edit'
      narrate_path
    end
  end


end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Narrater</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="google-site-verification" content="WLjGWoItM7j9YetwEBuOGMJnG0MFDVQKCPPsOC_nrkY" />

  </head>

  <body>
    <header class="header_area">
      <div class="container">
        <ul class="row">
          <li class="col-sm-8 col-md-2"><%= link_to 'HOME', root_path %></li>
          <li class="col-sm-8 col-md-2"><%= link_to 'つぶやき', narrates_path %></li>
          <li class="col-sm-8 col-md-2"><%= link_to '投稿', new_narrate_path %></li>
        </ul>
      </div>
    </header>

    <div class = "login_area" >
      <% if logged_in? %>
        <%= link_to "マイページ", user_path(current_user.id) %>
        <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
      <% else %>
        <%= link_to "新規登録", new_user_path %>
        <%= link_to "ログイン", new_session_path %>
      <% end %>
    </div>

    <%= yield %>

    <fotter class="fotter_area">
      <p>tbt's test application</p>
    </fotter>

  </body>
</html>

app/views/narrates/_errer.erb
<%= form_with(model: @narrate,local: true) do |form| %>

  <% if @narrate.errors.any? %>
    <div id="error_explanation">
      <h3 class="alert alert-danger">※つぶやきが空白または140字以上です。再度入力してください。</h3>
    </div>
  <% end %>
<% end %>

app/views/narrates/_form.html.erb
  <%= form_with(model: @narrate,local:true ,url: choose_new_or_edit) do |form| %>
    <div class="narate_content">
      <%= form.label :つぶやき： %>
      <%= form.text_field :content %>
    </div>
    <div class="narate_image">
      <% if @narrate.image.url %>
        <label> 画像：</label>
        <P><%= @narrate.image.url%><p>
        <div>
          <%= form.label :画像を変更する： %>
          <%= form.file_field :image %>
          <%= form.hidden_field :image_cache %>
        </div>
      <% else %>
      <%= form.label :画像： %>
      <%= form.file_field :image %>
      <% end %>
    </div>

    <div class="submit">
      <%= form.submit "投稿" ,:class=>"btn btn-default" %>
    </div>
  <% end %>

app/views/narrates/confirm.html.erb
<h3 class="form_navigation">以下の内容で投稿しますか?</h3>

<div class="confirm_content">
  <%= form_with(model: @narrate, url: narrates_path,local:true) do |form| %>
    <%= form.hidden_field :content %>
    <%= form.hidden_field :image_cache %>
    <% if  @user.image? %>
      <a class="confirm_icon"><%= image_tag @user.image %></a>
    <% else %>
      <a class="confirm_icon"><img src="/images/icon.png"></a>
    <% end %>
    <q class="confirm_balloon">
      <%= @narrate.content %>
      <% if @narrate.image? %>
        <p class="confirm_image"><%= image_tag (@narrate.image) %></p>
      <% end %>
    </q>
    <div class="submit">
      <%= form.submit "投稿" ,:class=>"btn" %>
    </div>
  <% end %>

  <%= form_with(model: @narrate, url: new_narrate_path,local:true, method: 'get') do |form| %>
    <div class="submit">
      <%= form.hidden_field :content %>
      <%= form.hidden_field :image_cache %>
      <%= form.submit "戻る", name: 'back' ,:class=>"btn" %>
    </div>
  <% end %>

</div>

app/views/narrates/edit.html.erb
<%= render "errer" %>

<h3 class="form_navigation">つぶやきを編集する</h3>

<%= render "form" %>

app/views/narrates/home.html.erb
<div class="home_info">
  <h1>Narrater</h1>
  <p>Narraterは簡単なつぶやきを投稿することのできるアプリです。</p>
  <ul>
    <li>つぶやきを投稿するにはログインが必要です。アカウントをお持ちでなければ新規登録をお願いします。</li>
    <li>つぶやきを投稿・編集・削除・一覧表示することができます。</li>
    <li>つぶやきは、１字以上１４０字以下でないと投稿できません。</li>
  </ul>
</div>

app/views/narrates/index.html.erb
<h3><%= notice %></h3>

<table>
    <h3 class="navigation">つぶやき一覧</h3>

  <% @narrates.each do |narrate| %>
    <tr class="content">
      <td>
        <% if  narrate.user.image? %>
          <p class="icon"><%= image_tag narrate.user.image %></p>
        <% else %>
          <p class="icon"><img src="/images/icon.png"></p>
        <% end %>
        <p class="user_name"><%= narrate.user.name %></p>
      <td>
      <td class="balloon">
        <p><%= narrate.content %></p>
        <% if  narrate.image? %>
          <p class="content_image"><%= image_tag narrate.image %></p>
        <% end %>
      </td>

      <% if narrate.user == current_user %>
        <td type="button" class="btn btn-default" >
          <%= link_to'編集',edit_narrate_path(narrate.id) , data: { confirm: '本当に編集してよろしいですか？' }%>
        </td>
        <td type="button" class="btn btn-default">
          <%= link_to '削除',narrate_path(narrate.id) , method: :delete , data: { confirm: '本当に削除してよろしいですか？' }%>
        </td>
      <% else %>
        <% @favorite = current_user.favorites.find_by(narrate_id: narrate.id) %>
        <% if @favorite.present? %>
          <td type="button" class="btn btn-info" >
            <%= link_to 'お気に入り解除', favorite_path(id: @favorite.id), method: :delete%>
          <td>
        <% else %>
          <td type="button" class="btn btn-default" >
            <%= link_to 'お気に入りする', favorites_path(narrate_id: narrate.id), method: :post %>
          <td>
        <% end %>
      <% end %>
    </tr>
    <tr class="spacer"></tr>
  <% end %>
</table>

app/views/narrates/new.html.erb
<%= render "errer" %>

<h3 class="form_navigation">新規投稿する</h3>

<%= render "form" %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count,"") %> 件のエラーがあります</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="home_info">
  <h2>アカウント新規登録</h2>

  <%= form_with(model: @user, local: true) do |f| %>
    <div class="">
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :"password(確認)" %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="">
      <%= f.submit "作成" ,:class=>"btn btn-default" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h3><%= notice %></h3>
<h3 class="form_navigation"><%= @user.name %>のページ</h3>

<div class="home_info">
  <h3>メールアドレス: <%= @user.email %>
  <div>
    <tr>現在のアイコン：</tr>
    <% if @user.image? %>
      <td class="icon"><%= image_tag @user.image %></td>
    <% else %>
      <td class="icon"><img src="/images/icon.png"></td>
    <% end %>
  </div>
  <div class="icon_edit">
    <%= form_with(model: @user, local: true ) do |form| %>
        <%= form.label :アイコンを変更する %>
        <%= form.file_field :image %>
        <%= form.submit "変更する" ,:class=>"btn btn-default" %>
    <% end %>
  </div>
</div>


<table>
    <h3 class="navigation">お気に入りのつぶやき</h3>

  <% @fav_narrates.each do |narrate| %>
    <tr class="content">
      <td>
        <% if  narrate.user.image? %>
          <p class="icon"><%= image_tag narrate.user.image %></p>
        <% else %>
          <p class="icon"><img src="/images/icon.png"></p>
        <% end %>
        <p class="user_name"><%= narrate.user.name %></p>
      </td>
      <td class="balloon">
        <%= narrate.content %>
        <% if  narrate.image? %>
          <p><%= image_tag narrate.image %></p>
        <% end %>
      </td>
      <% @favorite = current_user.favorites.find_by(narrate_id: narrate.id) %>
        <td type="button" class="btn btn-info" >
          <%= link_to 'お気に入り解除', favorite_path(id: @favorite.id), method: :delete%>
        <td>
    </tr>
    <tr class="spacer"></tr>
  <% end %>
</table>